eureka:
  client:
    enabled: false

server:
  port: 8080

spring:
  application:
    name: post-service

  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS

    request:
      timeout: 10s

    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

    local-datacenter: datacenter_1

    keyspace-name: high_five