eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 11111

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: ${DB_URI:mongodb://localhost:27017/high-five}
      database: high-five
      uuid-representation: standard